### ISSUE TITLE
tilia api app fails for some parameterized functions

### ISSUE THREAD

**Issue by stryker-m** [NeotomaDB/tilia_api#3]
The syntax generated by pg_function creates a statement using the explicit parameter name.  For functions defined with parameter type but not an alias, these calls fails.  See getcollunitbyidv2 vs getcollunitbyid.  Possible fixes are to always pass parameter values in the correct order or update function definitions to provided the parameter alias. @SimonGoring

**Comment by SimonGoring** [comment]
How many functions are being defined without explicit parameter names?  We should avoid that in general I think.

**Comment by SimonGoring** [comment]
Okay, I took a look.  So, from now on:

1. All functions should use the same parameter nameset as the functions they are replacing.
2. We need to make sure that Eric is explicitly using parameters, otherwise we also have to add a check to see if the parameters are in the same order.

@stryker-m you can drop functions (or I can), and using that procedure we can repair the functions that semi-fail using `python3 check-tilia.py`, e.g., ones with output like this:

```
Match with unmatched parameters: getchronconroltypebyname
New:
['cctype']
['chroncontroltype']
Missing: getchroncontroltypehighestid
Missing: getchronocontrolsbyanalysisunitid
Match with unmatched parameters: getchronocontrolsbychronologyid
New:
['cronid']
['chronologyid']
Match with unmatched parameters: getchronologiesbycollunitid
New:
['collunitid']
['collectionunitid']
Match with unmatched parameters: getcollectiontypebyid
New:
['integer']
['colltypeid']
Match with unmatched parameters: getcollector
New:
['integer']
['collectionunitid']
Match with unmatched parameters: getcollunitbyid
New:
['integer']
['collectionunitid']
Match with unmatched parameters: getcollunithandlecount
New:
['hand']
['handle']
```

**Comment by stryker-m** [comment]
I think we'll have a challenge here. We have all created functioned owned
by our own accounts.  I can't drop functions I didn't create.  We're need
to create rights to each other or create a role that accomplishes the same
thing.

**Comment by SimonGoring** [comment]
I agree, I think we can manage this in Madison.  If we stick to consistent re-naming of params we should be fine though.
